version: "3.8"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: employee_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: ""
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./api
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user  
      - DB_PASSWORD=
      - DB_NAME=employee_manager

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data: